

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laundryapplication;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author WINDOWS10
 */
public class tampilanGui extends javax.swing.JFrame {
    Data_diri dtdiri=new Data_diri();
    Seleksi pilih=new Seleksi();
    Perhitungan hitung=new Perhitungan();
    /**
     * Creates new form tampilanGui
     */
    public tampilanGui() {
        initComponents();
    }
    int hari = 0;
    public void getTglSelesai(int hari){
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.DAY_OF_YEAR, hari);
        Date hrSelesai = calendar.getTime();
        String formattedDate = formatter.format(hrSelesai);
        selesaiTextField.setText((pilih.getNb()== 0)?"":formattedDate);
        selesaiTextField.setEditable(pilih.getNb()== 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        simpanButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bersihButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();
        serviceComboBox = new javax.swing.JComboBox<>();
        barangComboBox = new javax.swing.JComboBox<>();
        namaTextField = new javax.swing.JTextField();
        hpTextField = new javax.swing.JTextField();
        terimaTextField = new javax.swing.JTextField();
        selesaiTextField = new javax.swing.JTextField();
        beratTextField = new javax.swing.JTextField();
        hargaTextField = new javax.swing.JTextField();
        tbayarTextField = new javax.swing.JTextField();
        dpTextField = new javax.swing.JTextField();
        sbayarTextField = new javax.swing.JTextField();
        cucisetrikaCheckBox = new javax.swing.JCheckBox();
        cuciCheckBox = new javax.swing.JCheckBox();
        setrikaCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        belumbayarRadioButton = new javax.swing.JRadioButton();
        lunasRadioButton = new javax.swing.JRadioButton();
        LDButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        simpanButton.setText("Simpan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI LAUNDRY");

        jLabel2.setText("Nama");

        jLabel13.setText("Total Bayar");

        jLabel3.setText("Alamat");

        jLabel14.setText("DP");

        jLabel4.setText("Nomor HP");

        jLabel15.setText("Sisa Bayar");

        jLabel5.setText("Tanggal Terima");

        jLabel6.setText("Tanggal Selesai");

        jLabel7.setText("Service");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Berat/Kg");

        jLabel11.setText("Harga");

        bersihButton.setText("Bersih");
        bersihButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihButtonActionPerformed(evt);
            }
        });

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        serviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Reguler", "Express" }));
        serviceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceComboBoxActionPerformed(evt);
            }
        });

        barangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pakaian", "Selimut", "Bed Cover", " " }));
        barangComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangComboBoxActionPerformed(evt);
            }
        });

        namaTextField.setToolTipText("");
        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        hpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpTextFieldActionPerformed(evt);
            }
        });

        terimaTextField.setBackground(new java.awt.Color(204, 204, 204));
        terimaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaTextFieldActionPerformed(evt);
            }
        });

        beratTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beratTextFieldKeyReleased(evt);
            }
        });

        hargaTextField.setEditable(false);
        hargaTextField.setBackground(new java.awt.Color(204, 204, 204));
        hargaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTextFieldActionPerformed(evt);
            }
        });

        tbayarTextField.setEditable(false);
        tbayarTextField.setBackground(new java.awt.Color(204, 204, 204));
        tbayarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbayarTextFieldActionPerformed(evt);
            }
        });

        dpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpTextFieldActionPerformed(evt);
            }
        });
        dpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dpTextFieldKeyReleased(evt);
            }
        });

        sbayarTextField.setEditable(false);
        sbayarTextField.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroup2.add(cucisetrikaCheckBox);
        cucisetrikaCheckBox.setText("Cuci + Setrika ");
        cucisetrikaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cucisetrikaCheckBoxActionPerformed(evt);
            }
        });

        buttonGroup2.add(cuciCheckBox);
        cuciCheckBox.setText("Cuci ");
        cuciCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuciCheckBoxActionPerformed(evt);
            }
        });

        buttonGroup2.add(setrikaCheckBox);
        setrikaCheckBox.setText("Setrika (1 hari)");
        setrikaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setrikaCheckBoxActionPerformed(evt);
            }
        });

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        alamatTextArea.setAutoscrolls(false);
        jScrollPane1.setViewportView(alamatTextArea);

        jLabel16.setText("Pelayanan");

        jLabel12.setText("Pembayaran");

        buttonGroup1.add(belumbayarRadioButton);
        belumbayarRadioButton.setText("Belum Bayar");

        buttonGroup1.add(lunasRadioButton);
        lunasRadioButton.setText("Lunas");
        lunasRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunasRadioButtonActionPerformed(evt);
            }
        });

        LDButton.setText("Lihat Daftar");
        LDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(namaTextField)
                                                .addComponent(hpTextField)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(simpanButton)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(beratTextField)
                                            .addGap(93, 93, 93))
                                        .addComponent(hargaTextField))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(LDButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(keluarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sbayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lunasRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(belumbayarRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cuciCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(setrikaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cucisetrikaCheckBox)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(terimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(selesaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(19, 19, 19))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(bersihButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(beratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cucisetrikaCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuciCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setrikaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(serviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(terimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selesaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(belumbayarRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lunasRadioButton)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tbayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sbayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel12))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keluarButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bersihButton)
                        .addComponent(simpanButton)
                        .addComponent(LDButton)))
                .addGap(14, 14, 14))
        );

        belumbayarRadioButton.getAccessibleContext().setAccessibleName("jRadioButton");
        lunasRadioButton.getAccessibleContext().setAccessibleName("jRadioButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String formattedDate = formatter.format(date);
        terimaTextField.setText(formattedDate);
        terimaTextField.setEditable(false);
    }//GEN-LAST:event_formWindowActivated

    private void terimaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terimaTextFieldActionPerformed

    private void hpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpTextFieldActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void lunasRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunasRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunasRadioButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void cucisetrikaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cucisetrikaCheckBoxActionPerformed
        // TODO add your handling code here:
       if (cucisetrikaCheckBox.isSelected()) {
           pilih.setCb(0);
           hargaTextField.setText(Double.toString(pilih.getHrg()));
           pilih.setNb(barangComboBox.getSelectedIndex());
           pilih.setService(serviceComboBox.getSelectedIndex());
           
//           String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
//           String totalHarga = Double.toString(pilih.getHrg() * Double.parseDouble(berat));
//           tbayarTextField.setText(totalHarga);
           String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
           hitung.setBerat(Double.parseDouble(berat));
            
           pilih.getProses();
            
           tbayarTextField.setText(Double.toString(hitung.getTb()));
           getTglSelesai(pilih.getTs());
       }
        
        
    }//GEN-LAST:event_cucisetrikaCheckBoxActionPerformed

    private void cuciCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuciCheckBoxActionPerformed
        if (cuciCheckBox.isSelected()) {
            pilih.setCb(1);
            hargaTextField.setText(Double.toString(pilih.getHrg()));
            pilih.setNb(barangComboBox.getSelectedIndex());
            pilih.setService(serviceComboBox.getSelectedIndex());
            String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
            hitung.setBerat(Double.parseDouble(berat));
            
            pilih.getProses();
            
            tbayarTextField.setText(Double.toString(hitung.getTb()));
            getTglSelesai(pilih.getTs());
       }
    }//GEN-LAST:event_cuciCheckBoxActionPerformed
                                            
                                          
    private void serviceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceComboBoxActionPerformed
        // TODO add your handling code here:
        pilih.setNb(barangComboBox.getSelectedIndex());
        pilih.setService(serviceComboBox.getSelectedIndex());
//     int selectedServices = pilih.getService();
//     if (selectedServices==2){
//         
//     }         
        String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
        hitung.setBerat(Double.parseDouble(berat));
            
        pilih.getProses();
            
        tbayarTextField.setText(Double.toString(hitung.getTb()));
        
        
        getTglSelesai(pilih.getTs());        
    }//GEN-LAST:event_serviceComboBoxActionPerformed

    private void LDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDButtonActionPerformed
        // TODO add your handling code here:
        tampilanDB page2 = new tampilanDB();
        page2.setVisible(true);
    }//GEN-LAST:event_LDButtonActionPerformed

    private void barangComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangComboBoxActionPerformed
        // TODO add your handling code here:
        pilih.setNb(barangComboBox.getSelectedIndex());
        int selectedNb = pilih.getNb();
//        boolean state = (selectedNb > 0 && seectedNb == 1);
//        cucisetrikaCheckBox.setSelected(state);
//        cuciCheckBox.setEnabled(state);
//        setrikaCheckBox.setEnabled(state);
        pilih.getProses();
      
    }//GEN-LAST:event_barangComboBoxActionPerformed

    private void setrikaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setrikaCheckBoxActionPerformed
        // TODO add your handling code here:
        if (setrikaCheckBox.isSelected()) {
            pilih.setCb(2);
            pilih.setNb(barangComboBox.getSelectedIndex());
            pilih.setService(serviceComboBox.getSelectedIndex());
            hargaTextField.setText(Double.toString(pilih.getHrg()));
            
            String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
            hitung.setBerat(Double.parseDouble(berat));
            
            pilih.getProses();
            
            tbayarTextField.setText(Double.toString(hitung.getTb()));
            getTglSelesai(pilih.getTs());
       }
    }//GEN-LAST:event_setrikaCheckBoxActionPerformed

    private void hargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTextFieldActionPerformed

    private void beratTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratTextFieldKeyReleased
        // TODO add your handling code here:
        String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
        hitung.setBerat(Double.parseDouble(berat));
        pilih.getProses();
        tbayarTextField.setText(Double.toString(hitung.getTb()));
//        String berat = (beratTextField.getText().isEmpty()) ? "0" : beratTextField.getText();
//        String totalHarga = Double.toString(pilih.getHrg() * Double.parseDouble(berat));
//        tbayarTextField.setText(pilih.getProses());
    }//GEN-LAST:event_beratTextFieldKeyReleased

    private void dpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpTextFieldActionPerformed

    private void dpTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpTextFieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dpTextFieldKeyReleased

    private void bersihButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihButtonActionPerformed
        // TODO add your handling code here:
        alamatTextArea.setText("");
        beratTextField.setText("");
        dpTextField.setText("");
        hargaTextField.setText("");
        namaTextField.setText("");  
        hpTextField.setText("");
        buttonGroup2.clearSelection();
        buttonGroup1.clearSelection();
        sbayarTextField.setText("");
        tbayarTextField.setText("");
        selesaiTextField.setText("");
        barangComboBox.setSelectedIndex(0);
        serviceComboBox.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_bersihButtonActionPerformed

    private void tbayarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbayarTextFieldActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_tbayarTextFieldActionPerformed

   
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilanGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LDButton;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JComboBox<String> barangComboBox;
    private javax.swing.JRadioButton belumbayarRadioButton;
    private javax.swing.JTextField beratTextField;
    private javax.swing.JButton bersihButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cuciCheckBox;
    private javax.swing.JCheckBox cucisetrikaCheckBox;
    private javax.swing.JTextField dpTextField;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JTextField hpTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluarButton;
    private javax.swing.JRadioButton lunasRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField sbayarTextField;
    private javax.swing.JTextField selesaiTextField;
    private javax.swing.JComboBox<String> serviceComboBox;
    private javax.swing.JCheckBox setrikaCheckBox;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField tbayarTextField;
    private javax.swing.JTextField terimaTextField;
    // End of variables declaration//GEN-END:variables

    
 }
